-- Migration 010: Case Tasks (Checklist system)
CREATE TABLE IF NOT EXISTS case_tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    parent_task_id INT NULL,
    assigned_to INT NULL,
    title VARCHAR(255) NOT NULL,
    task_number VARCHAR(20) NULL,
    phase VARCHAR(100) NOT NULL,
    stage VARCHAR(100) NOT NULL,
    phase_order INT DEFAULT 0,
    stage_order INT DEFAULT 0,
    sort_order INT DEFAULT 0,
    status ENUM('not_started','in_progress','done','na') DEFAULT 'not_started',
    priority ENUM('low','normal','high','urgent') DEFAULT 'normal',
    is_conditional TINYINT(1) DEFAULT 0,
    condition_value VARCHAR(10) NULL,
    condition_answer VARCHAR(10) NULL,
    has_subtasks TINYINT(1) DEFAULT 0,
    due_date DATE NULL,
    notes TEXT NULL,
    completed_at DATETIME NULL,
    completed_by INT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (parent_task_id) REFERENCES case_tasks(id) ON DELETE CASCADE,
    INDEX idx_ct_case (case_id),
    INDEX idx_ct_phase (case_id, phase_order),
    INDEX idx_ct_parent (parent_task_id),
    INDEX idx_ct_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
